### ISSUE TITLE
Correct text formatting using spaces and returns

### ISSUE THREAD

**Issue by CacheStacks** [b-jesch/service.nfo.updater#2]
From:

\<watched\>true\</watched\>\<playcount\>1\</playcount\>

To:

    <watched>true</watched>
    <playcount>1</playcount>

Cheers! 🤖

**Comment by b-jesch** [comment]
Formatting is correct, as example see 8 Days (8 Tage) S01E01 NFO here:

[8 Tage.S01E01.zip](https://github.com/b-jesch/service.nfo.updater/files/11573128/8.Tage.S01E01.zip)
