### ISSUE TITLE
[Feature Request] Add lastplayed

### ISSUE THREAD

**Issue by dpprdan** [b-jesch/service.nfo.updater#6]
Would you consider adding the `<lastplayed></lastplayed>` tag to the updater?

According to the Kodi wiki  ([Movies](https://kodi.wiki/view/NFO_files/Movies), [Episodes](https://kodi.wiki/view/NFO_files/Episodes)), it ought to be a date (`yyyy-mm-dd`). 
Tinymediamanager [adds it](https://gitlab.com/tinyMediaManager/tinyMediaManager/-/commit/78f1329003833afd889a0250ef0f70386eb77da9) as a timestamp `<lastplayed>2024-09-11 14:36:26</lastplayed>`, though.

It should be deleted when resetting the status to `unwatched`, or else you get

```xml
  <watched>false</watched>
  <playcount>0</playcount>
  <lastplayed>2024-09-11 14:36:26</lastplayed>
```

if it's been added before.

**Comment by b-jesch** [comment]
added: https://github.com/b-jesch/service.nfo.updater/commit/fcefffc40e30e9a7c694e46b062e4d72a9ccfd0f

**Comment by dpprdan** [comment]
Thanks! 

This does not yet delete the tag when marking an movie/episode as `unwatched`, does it? 
(Writing an empty tag `<lastplayed></lastplayed>` might also suffice?)

**Comment by b-jesch** [comment]
Hmm, the lasplayed tag was immediately removed by setting the status to unwatched via context menu here. Tested with several .nfo's. Don't know if this has done by a third party addon (Embuary helper maybe) or by Kodi core. 

Should be tested this with a vanilla Kodi installation.

**Comment by b-jesch** [comment]
And it's weired. Sometimes the <lastplayed> tag is removed from some nfo, sometimes not from other nfo. There is no recognizable pattern. ~~Next problem is the addon is not triggered when watched status has changed via user operations (context menu). It was not intended for this.~~

**Comment by b-jesch** [comment]
Removing `<lastplayed>` tag now when playcount is 0. Using pretty print to reformat xml code: https://github.com/b-jesch/service.nfo.updater/commit/367fbb55b24ff557246262ed41e1e3e275f74978

**Comment by b-jesch** [comment]
After an odyssey of attempts to get prettyxml to work correctly (prettyxml randomly inserts blank lines for no apparent reason), version 1.1.3 now works flawlessly under Windows and Linux.

Sorry for flooding the version history.
